#!/usr/bin/with-contenv bash

if [ -n "${UMASK_SET}" ] && [ -z "${UMASK}" ]; then
  echo -e "You are using a legacy method of defining umask\nplease update your environment variable from UMASK_SET to UMASK\nto keep the functionality after July 2021"
  umask ${UMASK_SET}
fi

chown abc:abc /manga -R
chown abc:abc /downloads -R

exec \
	s6-setuidgid abc python3 /app/Manga-Tagger/MangaTagger.py
