name: Python tests

on:
  - pull_request

jobs:
  build:
#    env:
#      DISPLAY: ":99.0"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ '3.8','3.9', ]
    name: Python ${{ matrix.python-version }} sample
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
      - run: pip install -r requirements.txt
      - name: Run the tests
        run: python3 -m unittest discover -s tests -t .
